Opifer\CmsBundle\Entity\Cron:
    type: entity
    table: cron
    repositoryClass: Opifer\CmsBundle\Repository\CronRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        command:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        expression:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        priority:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        state:
            type: string
            scale: 0
            length: 20
            unique: false
            nullable: false
            precision: 0
        lastError:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        startedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: started_at
        endedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: ended_at
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: created_at
            gedmo:
              timestampable:
                on: create
    lifecycleCallbacks: {  }
