Opifer\CmsBundle\Entity\Form:
    type: entity
    table: form
    repositoryClass: Opifer\FormBundle\Model\FormRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 128
        notificationEmail:
            type: string
            nullable: true
            column: notification_email
        requiresConfirmation:
            type: boolean
            column: requires_confirmation
        redirectUrl:
            type: string
            nullable: true
            column: redirect_url
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
        recaptchaEnabled:
            type: boolean
            column: recaptcha_enabled
    manyToOne:
        schema:
            targetEntity: Opifer\CmsBundle\Entity\Schema
            cascade:
                - persist
            joinColumns:
                schema_id:
                    referencedColumnName: id
    oneToMany:
        posts:
            targetEntity: Opifer\CmsBundle\Entity\Post
            mappedBy: form
            orderBy:
                id: DESC
