Opifer\ExpressionEngine\Expression\ExpressionCollection:
  exclusion_policy: NONE
  properties:
    conditions:
      type: "array<Opifer\ExpressionEngine\Expression\Expression>"
    operator:
      type: string
