parameters:
    opifer.eav.attribute_manager.class: 'Opifer\EavBundle\Model\AttributeManager'
    opifer.eav.eav_manager.class: 'Opifer\EavBundle\Manager\EavManager'
    opifer.eav.empty_value_listener.class: 'Opifer\EavBundle\EventListener\EmptyValueListener'
    opifer.eav.discriminator_listener.class: 'Opifer\EavBundle\EventListener\DiscriminatorListener'
    opifer.eav.form.attribute_type.class: 'Opifer\EavBundle\Form\Type\AttributeType'
    opifer.eav.form.date_picker_type.class: 'Opifer\EavBundle\Form\Type\DatePickerType'
    opifer.eav.form.datetime_picker_type.class: 'Opifer\EavBundle\Form\Type\DateTimePickerType'
    opifer.eav.form.eav_type.class: 'Opifer\EavBundle\Form\Type\EavType'
    opifer.eav.form.eav_value.class: 'Opifer\EavBundle\Form\Type\ValueType'
    opifer.eav.form.fauxtype.class: 'Opifer\EavBundle\Form\Type\FauxType'
    opifer.eav.form.option_type.class: 'Opifer\EavBundle\Form\Type\OptionType'
    opifer.eav.form.schema_type.class: 'Opifer\EavBundle\Form\Type\SchemaType'
    opifer.eav.form.schema_object_class_type.class: 'Opifer\EavBundle\Form\Type\SchemaObjectClassType'
    opifer.eav.form.value_provider_type.class: 'Opifer\EavBundle\Form\Type\ValueProviderType'
    opifer.eav.form.values_subscriber.class: 'Opifer\EavBundle\Form\EventListener\ValuesSubscriber'
    opifer.eav.form.values_type.class: 'Opifer\EavBundle\Form\Type\ValuesType'
    opifer.eav.form.valueset_type.class: 'Opifer\EavBundle\Form\Type\ValueSetType'
    opifer.eav.schema_manager.class: 'Opifer\EavBundle\Model\SchemaManager'
    opifer.eav.value_provider.pool.class: 'Opifer\EavBundle\ValueProvider\Pool'

services:
    # Values provider pool
    opifer.eav.value_provider.pool:
        class: '%opifer.eav.value_provider.pool.class%'

    opifer.eav.form.values_subscriber:
        class: '%opifer.eav.form.values_subscriber.class%'

    # Form Types

    opifer.eav.form.attribute_type:
        class: '%opifer.eav.form.attribute_type.class%'
        arguments: ['@form.factory', '@opifer.eav.value_provider.pool', '%opifer_eav.attribute_class%', '%opifer_eav.schema_class%']
        tags:
            - { name: form.type }

    opifer.eav.form.date_picker_type:
        class: '%opifer.eav.form.date_picker_type.class%'
        tags:
            - { name: form.type }

    opifer.eav.form.datetime_picker_type:
        class: '%opifer.eav.form.datetime_picker_type.class%'
        tags:
            - { name: form.type }

    opifer.eav.form.eav_value:
        class: '%opifer.eav.form.eav_value.class%'
        arguments: ['@opifer.eav.value_provider.pool']
        tags:
            - { name: form.type }

    opifer.eav.form.schema_object_class_type:
        class: '%opifer.eav.form.schema_object_class_type.class%'
        arguments: ['%opifer_eav.entities%']
        tags:
            - { name: form.type }

    opifer.eav.form.option_type:
        class: '%opifer.eav.form.option_type.class%'
        arguments: ['%opifer_eav.option_class%']
        tags:
            - { name: form.type }

    opifer.eav.form.eav_type:
        class: '%opifer.eav.form.eav_type.class%'
        tags:
            - { name: form.type }

    opifer.eav.form.schema_type:
        class: '%opifer.eav.form.schema_type.class%'
        arguments: ['%opifer_eav.schema_class%']
        tags:
            - { name: form.type }

    opifer.eav.form.valueset_type:
        class: '%opifer.eav.form.valueset_type.class%'
        arguments: ['%opifer_eav.valueset_class%']
        tags:
            - { name: form.type }

    opifer.eav.form.value_provider_type:
        class: '%opifer.eav.form.value_provider_type.class%'
        arguments: ['@opifer.eav.value_provider.pool']
        tags:
            - { name: form.type }

    opifer.eav.form.values_type:
        class: '%opifer.eav.form.values_type.class%'
        arguments: ['@opifer.eav.form.values_subscriber']
        tags:
            - { name: form.type }

    # Entity Managers
    opifer.eav.attribute_manager:
        class: '%opifer.eav.attribute_manager.class%'
        arguments: ['@doctrine.orm.default_entity_manager', '%opifer_eav.attribute_class%']

    opifer.eav.eav_manager:
        class: '%opifer.eav.eav_manager.class%'
        arguments: ['@opifer.eav.value_provider.pool', '%opifer_eav.valueset_class%']

    opifer.eav.schema_manager:
        class: '%opifer.eav.schema_manager.class%'
        arguments: ['@doctrine.orm.default_entity_manager', '%opifer_eav.schema_class%']

    # Listeners
    opifer.eav.discriminator_listener:
        class: '%opifer.eav.discriminator_listener.class%'
        arguments: ['@opifer.eav.value_provider.pool']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    opifer.eav.empty_value_listener:
        class: '%opifer.eav.empty_value_listener.class%'
        arguments: ['@opifer.eav.eav_manager']
        tags:
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: postPersist }
