language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

env:
  - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - travis_wait composer update --prefer-dist --no-interaction --no-scripts

script: phpunit --coverage-text
