language: php

sudo: false

php:
  - 7.3

cache:
  directories:
    - vendor

env:
  - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini;
  - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction --no-scripts

script: vendor/bin/phpunit --coverage-text
