language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

env:
  - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add etc/travis/before-install-php.ini
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction --no-scripts

script: phpunit --coverage-text
