language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

env:
  - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update

install:
  - php -d memory_limit=2G composer install --prefer-dist --no-interaction --no-scripts

script: phpunit --coverage-text
