language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: phpunit --coverage-text

branches:
  only:
    - master
    - develop
