twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        "%kernel.root_dir%/../vendor/opifer/cms/src/ExpressionEngine/Resources/views": OpiferExpressionEngine
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'OpiferEavBundle:Form:fields.html.twig'
        - 'OpiferMediaBundle:Form:fields.html.twig'
        - 'OpiferContentBundle:Form:fields.html.twig'
        - '@OpiferExpressionEngine/Form/fields.html.twig'
        - 'OpiferCmsBundle:Form:fields.html.twig'
    globals:
        config: '@opifer.cms.config_manager'
        content_type_manager: '@opifer.content.content_type_manager'
        google_tag_manager_key: '%opifer_cms.google_tag_manager_key%'
        recaptcha_site_key: '%opifer_form.recaptcha_site_key%'
