parameters:
    opifer.form.form_extension.class: 'Opifer\FormBundle\Twig\FormExtension'
    opifer.form.form_manager.class: 'Opifer\FormBundle\Model\FormManager'
    opifer.form.form_form.class: 'Opifer\FormBundle\Form\Type\FormType'
    opifer.form.post_form.class: 'Opifer\FormBundle\Form\Type\PostType'
    opifer.form.post_manager.class: 'Opifer\FormBundle\Model\PostManager'

services:
    # Form

    opifer.form.form_manager:
        class: '%opifer.form.form_manager.class%'
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@form.factory'
            - '@opifer.eav.schema_manager'
            - '@opifer.form.post_manager'
            - '%opifer_form.form_class%'
        public: true

    opifer.form.form_form:
        class: '%opifer.form.form_form.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%opifer_form.post_class%'
            - '%opifer_form.recaptcha_site_key%'
            - '%opifer_form.recaptcha_secret_key%'
        tags:
            - { name: form.type }

    # Post

    opifer.form.post_manager:
        class: '%opifer.form.post_manager.class%'
        arguments: ['@doctrine.orm.default_entity_manager', '%opifer_form.post_class%']
        public: true

    opifer.form.post_form:
        class: '%opifer.form.post_form.class%'
        arguments: ['@router']
        tags:
            - { name: form.type }

    # Twig

    opifer.form.form_extension:
        class: '%opifer.form.form_extension.class%'
        arguments: ['@opifer.eav.eav_manager', '@form.factory']
        public: false
        tags:
            - { name: twig.extension }

    # Mailer

    opifer.form.mailer:
        class: 'Opifer\FormBundle\Mailer\Mailer'
        arguments: ['@translator', '@request_stack', '@templating', '@mailer', '%opifer_form.from_email%']

    # Event Listeners

    opifer.form.notification_mail_listener:
        class: 'Opifer\FormBundle\EventListener\NotificationMailListener'
        arguments: ['@opifer.form.mailer']
        tags:
            - { name: kernel.event_subscriber }
