services:
    opifer.mailinglist.provider_pool:
        class: Opifer\MailingListBundle\Provider\ProviderPool

    opifer.mailinglist.subscription_manager:
        class: Opifer\MailingListBundle\Manager\SubscriptionManager
        arguments: ['@doctrine.orm.default_entity_manager']

    opifer.mailinglist.mailinglist_manager:
        class: Opifer\MailingListBundle\Manager\MailingListManager
        arguments: ['@doctrine.orm.default_entity_manager']

    opifer.mailinglist.mailplus_provider:
        class: Opifer\MailingListBundle\Provider\MailPlusProvider
        arguments: ['@opifer.mailinglist.subscription_manager', '%opifer_mailing_list.mailplus.consumer_key%', '%opifer_mailing_list.mailplus.consumer_secret%']
        tags:
            - { name: opifer.mailinglist.provider, alias: mailplus }

    opifer.mailinglist.activecampaign_provider:
            class: Opifer\MailingListBundle\Provider\ActiveCampaignProvider
            arguments: ['@opifer.mailinglist.subscription_manager', '%opifer_mailing_list.activecampaign.url%', '%opifer_mailing_list.activecampaign.key%']
            tags:
                - { name: opifer.mailinglist.provider, alias: activecampaign }

    opifer.mailinglist.mailchimp_provider:
        class: Opifer\MailingListBundle\Provider\MailChimpProvider
        arguments: ['@opifer.mailinglist.subscription_manager', '@opifer.cms.config_manager']
        tags:
            - { name: opifer.mailinglist.provider, alias: mailchimp }

    opifer.mailinglist.mailchimp_settings_form:
        class: Opifer\MailingListBundle\Form\Type\MailChimpSettingsType
        tags:
            - { name: opifer.configuration_form }

    opifer.mailinglist.mailinglist_type:
        class: Opifer\MailingListBundle\Form\Type\MailingListType
        arguments: ['@opifer.mailinglist.provider_pool']
        tags:
            - { name: form.type }

    opifer.mailinglist.mailinglists_type:
        class: Opifer\MailingListBundle\Form\Type\MailingListsType
        arguments: ['@opifer.mailinglist.mailinglist_manager']
        tags:
            - { name: form.type }
