services:
    opifer.subscription_manager:
        class: Opifer\MailingListBundle\Manager\SubscriptionManager
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: opifer.subscription_manager }

    opifer.mailplus_provider:
        class: Opifer\MailingListBundle\Provider\MailPlusProvider
        arguments: ['@opifer.subscription_manager', '%opifer_mailing_list.mailplus.consumer_key%', '%opifer_mailing_list.mailplus.consumer_secret%']
        tags:
            - { name: opifer.mailplus_provider }
