parameters:
    opifer.content.button_block.class: Opifer\ContentBundle\Block\Service\ButtonBlockService
    opifer.content.carousel_block.class: Opifer\ContentBundle\Block\Service\CarouselBlockService
    opifer.content.carousel_slide_block.class: Opifer\ContentBundle\Block\Service\CarouselSlideBlockService
    opifer.content.collection_block.class: Opifer\ContentBundle\Block\Service\CollectionBlockService
    opifer.content.iframe_block.class: Opifer\ContentBundle\Block\Service\IFrameBlockService
    opifer.content.card_block.class: Opifer\ContentBundle\Block\Service\CardBlockService
    opifer.content.column_block.class: Opifer\ContentBundle\Block\Service\ColumnBlockService
    opifer.content.container_block.class: Opifer\ContentBundle\Block\Service\ContainerBlockService
    opifer.content.section_block.class: Opifer\ContentBundle\Block\Service\SectionBlockService
    opifer.content.gallery_block.class: Opifer\ContentBundle\Block\Service\GalleryBlockService
    opifer.content.html_block.class: Opifer\ContentBundle\Block\Service\HtmlBlockService
    opifer.content.image_block.class: Opifer\ContentBundle\Block\Service\ImageBlockService
    opifer.content.jumbotron_block.class: Opifer\ContentBundle\Block\Service\JumbotronBlockService
    opifer.content.pointer_block.class: Opifer\ContentBundle\Block\Service\PointerBlockService
    opifer.content.list_block.class: Opifer\ContentBundle\Block\Service\ListBlockService
    opifer.content.navigation_block.class: Opifer\ContentBundle\Block\Service\NavigationBlockService
    opifer.content.tabnav_block.class: Opifer\ContentBundle\Block\Service\TabNavBlockService
    opifer.content.css_block.class: Opifer\ContentBundle\Block\Service\CssBlockService
    opifer.content.javascript_block.class: Opifer\ContentBundle\Block\Service\JavaScriptBlockService
    opifer.content.pointer_block.class: Opifer\ContentBundle\Block\Service\PointerBlockService
    opifer.content.socialshare_block.class: Opifer\ContentBundle\Block\Service\SocialShareBlockService
    opifer.content.clipboard_block.class: Opifer\ContentBundle\Block\Service\ClipboardBlockService
    opifer.content.video_block.class: Opifer\ContentBundle\Block\Service\VideoBlockService
    opifer.content.cookiewall_block.class: Opifer\ContentBundle\Block\Service\CookieWallBlockService
    opifer.content.downloads_block.class: Opifer\ContentBundle\Block\Service\DownloadsBlockService
    opifer.content.breadcrumbs_block.class: Opifer\ContentBundle\Block\Service\BreadcrumbsBlockService
    opifer.content.avatar_block.class: Opifer\ContentBundle\Block\Service\AvatarBlockService
    opifer.content.search_results_block.class: Opifer\ContentBundle\Block\Service\SearchResultsBlockService
    opifer.content.modal_block.class: Opifer\ContentBundle\Block\Service\ModalBlockService
    opifer.content.data_view_block.class: Opifer\ContentBundle\Block\Service\DataViewBlockService

services:
    opifer.content.alert_block:
        class: 'Opifer\ContentBundle\Block\Service\AlertBlockService'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.alert_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: alert }

    opifer.content.button_block:
        class: '%opifer.content.button_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.button_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: button }

    opifer.content.card_block:
        class: '%opifer.content.card_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.card_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: card }

    opifer.content.carousel_block:
        class: '%opifer.content.carousel_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.carousel_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: carousel }

    opifer.content.carousel_slide_block:
        class: '%opifer.content.carousel_slide_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.carousel_slide_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: carousel_slide }

    opifer.content.collection_block:
        class: '%opifer.content.collection_block.class%'
        arguments:
            - '@opifer.content.block_renderer'
            - '@opifer.doctrine_expression_engine'
            - '@opifer.content.content_manager'
            - '@opifer.content.content_type_manager'
            - '@opifer.eav.attribute_manager'
            - '%opifer_content.collection_block_configuration%'
        tags:
            - { name: opifer.content.block_service, alias: collection }

    opifer.content.content_item_block:
        class: 'Opifer\ContentBundle\Block\Service\ContentItemBlockService'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.content_item_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: content_item }

    opifer.content.gallery_block:
        class: '%opifer.content.gallery_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.gallery_block_configuration%', '@opifer.media.media_manager']
        tags:
            - { name: opifer.content.block_service, alias: gallery }

    opifer.content.html_block:
        class: '%opifer.content.html_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.html_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: html }

    opifer.content.image_block:
        class: '%opifer.content.image_block.class%'
        arguments: ['@opifer.content.block_renderer', '%liip_imagine.filter_sets%', '%opifer_content.image_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: image }

    opifer.content.jumbotron_block:
        class: '%opifer.content.jumbotron_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.jumbotron_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: jumbotron }

    opifer.content.list_block:
        class: '%opifer.content.list_block.class%'
        arguments: ['@opifer.content.block_renderer', '@opifer.content.content_manager', '%opifer_content.list_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: list }

    opifer.content.navbar_block:
        class: 'Opifer\ContentBundle\Block\Service\NavBarBlockService'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.navbar_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: navbar }

    opifer.content.navigation_block:
        class: '%opifer.content.navigation_block.class%'
        arguments: ['@opifer.content.block_renderer', '@opifer.content.content_manager', '%opifer_content.navigation_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: navigation }

    opifer.content.navlink_block:
        class: 'Opifer\ContentBundle\Block\Service\NavLinkBlockService'
        arguments:
            - '@opifer.content.block_renderer'
            - '@router'
            - '@opifer.content.content_manager'
            - '%opifer_content.navlink_block_configuration%'
        tags:
            - { name: opifer.content.block_service, alias: navlink }

    opifer.content_iframe_block:
        class: '%opifer.content.iframe_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.iframe_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: iframe }

    opifer.content.css_block:
        class: '%opifer.content.css_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.css_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: css }

    opifer.content.javascript_block:
        class: '%opifer.content.javascript_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.javascript_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: javascript }

    opifer.content.pointer_block:
        class: '%opifer.content.pointer_block.class%'
        arguments: ['@opifer.content.block_renderer', '@opifer.content.block_manager', '%opifer_content.pointer_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: pointer }

    opifer.content.section_block:
        class: '%opifer.content.section_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.section_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: section }

    opifer.content.container_block:
        class: '%opifer.content.container_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.container_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: container }

    opifer.content.column_block:
        class: '%opifer.content.column_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.column_block_configuration%', '@doctrine.orm.entity_manager']
        tags:
            - { name: opifer.content.block_service, alias: column }

    opifer.content.tabnav_block:
        class: '%opifer.content.tabnav_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.tabnav_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: tabnav }

    opifer.content.socialshare_block:
        class: '%opifer.content.socialshare_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.socialshare_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: socialshare }
        calls:
            - [setRequestStack, ['@request_stack']]

    opifer.content.clipboard_block:
        class: '%opifer.content.clipboard_block.class%'
        arguments: ['@opifer.content.block_manager', '@session']
        tags:
            - { name: opifer.content.block_service, alias: clipboard }

    opifer.content.video_block:
        class: '%opifer.content.video_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.video_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: video }

    opifer.content.cookiewall_block:
        class: '%opifer.content.cookiewall_block.class%'
        arguments: ['@opifer.content.block_renderer', '@session', '%opifer_content.cookiewall_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: cookiewall }

    opifer.content.downloads_block:
        class: '%opifer.content.downloads_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.downloads_block_configuration%', '@opifer.media.media_manager', '@service_container']
        tags:
            - { name: opifer.content.block_service, alias: downloads }

    opifer.content.breadcrumbs_block:
        class: '%opifer.content.breadcrumbs_block.class%'
        arguments: ['@opifer.content.block_renderer', '@opifer.content.content_manager', '%opifer_content.breadcrumbs_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: breadcrumbs }

    opifer.content.avatar_block:
        class: '%opifer.content.avatar_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.avatar_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: avatar }

    opifer.content.modal_block:
        class: '%opifer.content.modal_block.class%'
        arguments: ['@opifer.content.block_renderer', '%opifer_content.modal_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: modal }

    opifer.content.related_collection_block:
        class: 'Opifer\ContentBundle\Block\Service\RelatedCollectionBlockService'
        arguments:
            - '@opifer.content.block_renderer'
            - '@opifer.doctrine_expression_engine'
            - '@opifer.content.content_manager'
            - '@opifer.content.content_type_manager'
            - '@opifer.eav.attribute_manager'
            - '%opifer_content.related_collection_block_configuration%'
        tags:
            - { name: opifer.content.block_service, alias: related_collection }

    opifer.content.search_results_block:
        class: '%opifer.content.search_results_block.class%'
        arguments: ['@opifer.content.block_renderer', '@opifer.content.content_manager', '%opifer_content.search_results_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: search_results }
        calls:
            - [setRequest, ['@request_stack']]

    opifer.content.data_view_block:
        class: '%opifer.content.data_view_block.class%'
        arguments: ['@opifer.content.block_renderer', '@doctrine.orm.default_entity_manager', '%opifer_content.data_view_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: data_view }
