liip_imagine:
    filter_sets:
        jumbotron:
            filters:
                upscale: { min: [1920, 1280] }
                thumbnail: { size: [1920, 1280], mode: outbound, allow_upscale: true  }
            post_processors:
                jpegoptim: { max: 65 }
                pngquant: {}
        sm_11:
            quality: 80
            filters:
                thumbnail: { size: [250, 250], mode: outbound }
        md_11:
            quality: 80
            filters:
                thumbnail: { size: [500, 500], mode: outbound }
        lg_11:
            quality: 80
            filters:
                thumbnail: { size: [1000, 1000], mode: outbound }
        sm_43:
            quality: 80
            filters:
                thumbnail: { size: [400, 300], mode: outbound }
        md_43:
            quality: 80
            filters:
                thumbnail: { size: [800, 600], mode: outbound }
        lg_43:
            quality: 80
            filters:
                thumbnail: { size: [1600, 1200], mode: outbound }
        sm_34:
            quality: 80
            filters:
                thumbnail: { size: [300, 400], mode: outbound }
        md_34:
            quality: 80
            filters:
                thumbnail: { size: [600, 800], mode: outbound }
        lg_34:
            quality: 80
            filters:
                thumbnail: { size: [1200, 1600], mode: outbound }
        sm_32:
            quality: 80
            filters:
                thumbnail: { size: [300, 200], mode: outbound }
        md_32:
            quality: 80
            filters:
                thumbnail: { size: [600, 400], mode: outbound }
        lg_32:
            quality: 80
            filters:
                thumbnail: { size: [1200, 800], mode: outbound }
        sm_23:
            quality: 80
            filters:
                thumbnail: { size: [200, 300], mode: outbound }
        md_23:
            quality: 80
            filters:
                thumbnail: { size: [400, 600], mode: outbound }
        lg_23:
            quality: 80
            filters:
                thumbnail: { size: [800, 1200], mode: outbound }
        sm_169:
            quality: 80
            filters:
                thumbnail: { size: [400, 275], mode: outbound }
        md_169:
            quality: 80
            filters:
                thumbnail: { size: [800, 450], mode: outbound }
        lg_169:
            quality: 80
            filters:
                thumbnail: { size: [1600, 900], mode: outbound }
        sm_916:
            quality: 80
            filters:
                thumbnail: { size: [275, 400], mode: outbound }
        md_916:
            quality: 80
            filters:
                thumbnail: { size: [450, 800], mode: outbound }
        lg_916:
            quality: 80
            filters:
                thumbnail: { size: [900, 1600], mode: outbound }
                