# Uncomment to test or allow access to single blocks
#opifer_content_block_view:
#    path: /block/{id}
#    defaults: { _controller: OpiferContentBundle:Frontend/Block:view }
#    requirements:
#        id: \d+
