imports:
    - { resource: doctrine_extensions.yml }
    - { resource: "@OpiferContentBundle/Resources/config/imagine.yml" }

parameters:
    grid.class: Opifer\CmsBundle\Grid\Grid
    locale: '%opifer_cms.default_locale%'

# CmsBundle config
#
# Default configuration for the CmsBundle and all it's dependencies.
# Application specific configuration should be located inside the main config
# file at app/config/config.yml
framework:
    ide:             'phpstorm://open?file=%%f&line=%%1'
    esi:             { enabled: true }
    translator:      { fallback: ['%opifer_cms.default_locale%', en] }
    secret:          '%secret%'
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  '%opifer_cms.default_locale%'
    session:
        handler_id: session.handler.native_file
        save_path: null #%kernel.root_dir%/../var/sessions
        cookie_lifetime: 604800
        cookie_secure: true
    fragments:       ~
    http_method_override: true
    php_errors:
        log: true

# Templating
#braincrafted_bootstrap:
#    output_dir:
#    auto_configure:
#        assetic:       false
#        twig:          true
#    customize:
#        variables_file:     ~
#        bootstrap_output:   '%kernel.root_dir%/Resources/less/bootstrap.less'
#        bootstrap_template: 'BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig'

# Routing
cmf_routing:
    chain:
        routers_by_id:
            # Redirect urls to other pages
            opifer.redirect.redirect_router: 300
            # The default symfony router
            router.default: 200
            # Checks the database for content items and routes to them if they exist.
            opifer.content.content_router: 100
            # Catch any routes and redirect them to a 404 page.
            opifer.cms.exception_router: 1

fos_js_routing:
    cache_control:
        # All are optional, defaults shown
        public: true   # can be true (public) or false (private)
        maxage: 3600    # integer value, e.g. 300
        smaxage: 3600   # integer value, e.g. 300
        expires: "1 day"    # anything that can be fed to "new \DateTime($expires)", e.g. "5 minutes"
        vary: []        # string or array, e.g. "Cookie" or [ Cookie, Accept ]

# Doctrine
doctrine:
    dbal:
        driver:   '%opifer_cms.database_driver%'
        host:     '%opifer_cms.database_host%'
        port:     ~
        dbname:   '%opifer_cms.database_name%'
        user:     '%opifer_cms.database_user%'
        password: '%opifer_cms.database_password%'
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping:                true
        dql:
            string_functions:
                DAYOFWEEK:  'DoctrineExtensions\Query\Mysql\DayOfWeek'
        filters:
            softdeleteable:
                class:   'Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter'
                enabled: true
            draft:
                class:   Opifer\Revisions\Filter\DraftFilter
                enabled: true
        resolve_target_entities:
            FOS\UserBundle\Model\UserInterface: '%opifer_cms.user_model%'
        mappings:
            translatable:
                type:   annotation
                alias:  Gedmo
                prefix: Gedmo\Translatable\Entity
                dir:    '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity'
            tree:
                type:   annotation
                alias:  Gedmo
                prefix: Gedmo\Tree\Entity
                dir:    '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity'

# Migrations
doctrine_migrations:
    dir_name:   '%kernel.root_dir%/../src/AppBundle/Migrations'
    namespace:  'AppBundle\Migrations'
    table_name: '%opifer_cms.database_table_prefix%migrations'
    name:       'Opifer Cms Migrations'

# Users
fos_user:
    db_driver:       'orm'
    firewall_name:   'main'
    user_class:      '%opifer_cms.user_model%'
    group:
        group_class: 'Opifer\CmsBundle\Entity\Group'
    registration:
        form:
            # Use our own registration form so we can remove the username field
            type:              public_registration_form
            name:              public_registration
            validation_groups: []
    from_email:
        address: noreply@jstack.eu
        sender_name: jstack CMS

# Framework extra
sensio_framework_extra:
    cache:   { annotations: true }
    view:    { annotations: true }
    router:  { annotations: true }
    request: { converters: true }

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        "%kernel.root_dir%/../vendor/opifer/cms/src/ExpressionEngine/Resources/views": OpiferExpressionEngine
    form_themes:
        - 'OpiferEavBundle:Form:fields.html.twig'
        - 'OpiferMediaBundle:Form:fields.html.twig'
        - 'OpiferContentBundle:Form:fields.html.twig'
        - '@OpiferExpressionEngine/Form/fields.html.twig'
        - 'OpiferCmsBundle:Form:fields.html.twig'
    globals:
        config: '@opifer.cms.config_manager'
        content_type_manager: '@opifer.content.content_type_manager'
        google_tag_manager_key: '%opifer_cms.google_tag_manager_key%'
        recaptcha_site_key: '%opifer_form.recaptcha_site_key%'

# Media
opifer_media:
    media:
        class: 'Opifer\CmsBundle\Entity\Media'
        views:
            index: 'OpiferCmsBundle:Backend\Media:index.html.twig'
            create: 'OpiferCmsBundle:Backend\Media:create.html.twig'
            edit: 'OpiferCmsBundle:Backend\Media:edit.html.twig'
    default_storage: '%storage_adapter%'
    providers:
        youtube:
            api_key: '%google_api_key%'
    storages:
        aws_s3:
            key:    '%amazon_s3_key%'
            secret: '%amazon_s3_secret%'
            region: '%amazon_s3_region%'
            bucket: '%amazon_s3_bucket%'
    cache_provider: 'Doctrine\Common\Cache\ApcuCache'

liip_imagine:
    filter_sets:
        inline:
            quality: 80
            filters:
                thumbnail: {size: [800, 600], mode: inset}
            post_processors:
                jpegoptim: {}
        dashboard_content:
            quality: 85
            filters:
                thumbnail: { size: [400, 300], mode: outbound}
        media_sm:
            quality: 70
            filters:
                relative_resize: {heighten: 160}
        avatar:
            quality: 80
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        content_list:
            quality: 80
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

apy_data_grid:
    pagerfanta:
        enable: true
        view_class: Pagerfanta\View\TwitterBootstrap3View

# Content
opifer_content:
    content_manager: 'opifer.cms.content_manager'
    cache_provider: 'Doctrine\Common\Cache\ApcuCache'
    content:
        class: Opifer\CmsBundle\Entity\Content
        views:
            index: 'OpiferCmsBundle:Backend/Content:index.html.twig'
            type: 'OpiferCmsBundle:Backend/Content:type.html.twig'
            new: 'OpiferCmsBundle:Backend/Content:new.html.twig'
            design: 'OpiferCmsBundle:Backend/Content:design.html.twig'
            details: 'OpiferCmsBundle:Backend/Content:details.html.twig'
            history: 'OpiferCmsBundle:Backend/Content:history.html.twig'
    content_type:
        class: Opifer\CmsBundle\Entity\ContentType
        views:
            index: 'OpiferCmsBundle:Backend/ContentType:index.html.twig'
            create: 'OpiferCmsBundle:Backend/ContentType:create.html.twig'
            edit: 'OpiferCmsBundle:Backend/ContentType:edit.html.twig'
    block:
        views:
            shared: 'OpiferCmsBundle:Backend/Block:shared.html.twig'

opifer_eav:
    attribute_class: Opifer\CmsBundle\Entity\Attribute
    media_class:     Opifer\CmsBundle\Entity\Media
    option_class:    Opifer\CmsBundle\Entity\Option
    schema_class:  Opifer\CmsBundle\Entity\Schema
    valueset_class:  Opifer\CmsBundle\Entity\ValueSet
    entities:
        content: 'Opifer\CmsBundle\Entity\Content'
        post: 'Opifer\CmsBundle\Entity\Post'

opifer_form:
    from_email: 'info@opifer.nl'
    form:
        class: 'Opifer\CmsBundle\Entity\Form'
        views:
            index: 'OpiferCmsBundle:Backend/Form:index.html.twig'
            create: 'OpiferCmsBundle:Backend/Form:create.html.twig'
            edit: 'OpiferCmsBundle:Backend/Form:edit.html.twig'
    post:
        class: 'Opifer\CmsBundle\Entity\Post'
        views:
            index: 'OpiferCmsBundle:Backend/Post:index.html.twig'
            view: 'OpiferCmsBundle:Backend/Post:view.html.twig'

opifer_redirect:
    redirect:
        class: 'Opifer\CmsBundle\Entity\Redirect'
        views:
            index: 'OpiferCmsBundle:Backend/Redirect:index.html.twig'
            create: 'OpiferCmsBundle:Backend/Redirect:create.html.twig'
            edit: 'OpiferCmsBundle:Backend/Redirect:edit.html.twig'

opifer_cms:
    ckeditor:
        css_path: '/bundles/opifercms/css/app.css'
    autocomplete:
        user:
            class: 'Opifer\CmsBundle\Entity\User'
            property: 'email'

opifer_review:
    review:
        class: 'Opifer\CmsBundle\Entity\Review'
        views:
            index: 'OpiferCmsBundle:Backend/Review:index.html.twig'
            create: 'OpiferCmsBundle:Backend/Review:create.html.twig'
            edit: 'OpiferCmsBundle:Backend/Review:edit.html.twig'



# Nelmio CORS
nelmio_cors:
    defaults:
        forced_allow_origin_value: '*'
    paths:
        '^/(admin/api|api|accept-cookies)':
            allow_credentials: true
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+', '^http://127.0.0.1:[0-9]+', '^http://[a-z0-9-]+.dev:[0-9]+']
            allow_headers: ['origin', 'x-custom-auth', 'authorization', 'content-type', 'accept', 'x-requested-with']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600

# FOS Rest
fos_rest:
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors # This is the default value
    format_listener:
        rules:
            - { path: '^/admin/api', priorities: ['json', 'html'], fallback_format: json, prefer_extension: false }
            - { path: '^/api', priorities: ['json', 'html'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true

#2FA
scheb_two_factor:
    google:
        template: OpiferCmsBundle:Security:google_2fa_form.html.twig
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Acme\AuthenticationBundle\Token\CustomAuthenticationToken

# Nelmio API Documentation
nelmio_api_doc: ~

# Lexik JWT
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'

lexik_translation:
    fallback_locale: [en]         # (required) default locale(s) to use
    managed_locales: [en, nl] # (required) locales that the bundle has to manage
    base_layout: 'OpiferCmsBundle:Backend/Translation:base.html.twig'
