<?php

namespace Opifer\ContentBundle\Model;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * DirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectoryRepository extends NestedTreeRepository
{
}
