<?php

namespace Opifer\ContentBundle\Repository;

/**
 * DataViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataViewRepository extends \Doctrine\ORM\EntityRepository
{
}
