# Routing used by multiple bundles
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

opifer_revision:
    resource: '@OpiferRevisionsBundle/Resources/config/routing.yml'

fos_user_security_check:
    pattern: /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    methods: [POST]

fos_user_security_logout:
    pattern: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

# Opifer bundle routing

opifer_cms_exception_404:
    pattern: /404
    defaults: { _controller: OpiferCmsBundle:Frontend\Exception:error404 }
    methods: [GET]

opifer_form:
    resource: "@OpiferFormBundle/Resources/config/routing.yml"

opifer_cms_home:
    pattern:  /
    defaults: { _controller: OpiferContentBundle:Frontend\Content:home }
    options: {sitemap: true}

opifer_cms_auto_complete:
    path: /autocomplete/{alias}
    defaults: { _controller: OpiferCmsBundle:AutoComplete:query }
    options:
        expose: true

opifer_cms_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

# Third party bundle routing fallbacks

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_user_change_password:
    pattern:  /change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods:  [GET,POST]

_opifer_backend:
    resource: "routing_backend.yml"
    prefix:   /admin


# Block Services

opifer_mailing_list_subscribe_block:
    pattern: /subscribe/{id}
    defaults: { _controller: opifer.mailing_list.subscribe_block:subscribeAction }

opifer_cookie_wall_block:
    pattern: /accept-cookies/{id}
    defaults: { _controller: opifer.content.cookiewall_block:acceptCookiesAction }