name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.1', '7.2']

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs --no-scripts --optimize-autoloader

      - name: Run tests
        run: composer run-script test
